// Copyright 2026 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

package goodhistogram

import (
	"flag"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// Each file in ../datatest is one self-contained scenario. It has a
// hand-authored input section (the histogram params and the values to record)
// and a generated golden section (the OpenMetrics exposition plus a set of
// quantiles). The Go implementation is the source of truth: `-rewrite`
// regenerates the golden section from live Go. A normal run replays the values
// and checks the live output matches the committed golden — counts and sum
// exactly, boundaries and quantiles within a small tolerance so platform (libm)
// differences in the float math don't cause spurious failures.
//
// The Rust crate (rust/tests/datatest.rs) reads the SAME files, replays the
// values against its own implementation, and checks it reproduces the golden.
// So the two implementations are pinned to one shared, human-readable contract;
// any divergence fails CI on one side or the other. See datatest/README.md.
//
// Regenerate with:
//
//	go test ./go/ -run TestDatatest -rewrite
var rewriteDatatest = flag.Bool("rewrite", false,
	"regenerate the golden section of every datatest/*.txt from the Go implementation")

const (
	datatestDir = "../datatest"
	metricName  = "goodhistogram"
	genMarker   = "# --- generated by `go test ./go/ -run TestDatatest -rewrite`; do not edit below ---"
)

// datatestQuantiles is the set queried for every scenario: min, p25, median,
// p75, p90, p95, p99, p99.99, p99.999, max.
var datatestQuantiles = []float64{0, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99, 0.9999, 0.99999, 1}

// datatestInput is the hand-authored half of a scenario file.
type datatestInput struct {
	lo, hi, errorBound float64
	values             []int64
}

func TestDatatest(t *testing.T) {
	files, err := filepath.Glob(filepath.Join(datatestDir, "*.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if len(files) == 0 {
		t.Fatalf("no scenarios found in %s", datatestDir)
	}
	sort.Strings(files)
	for _, f := range files {
		t.Run(strings.TrimSuffix(filepath.Base(f), ".txt"), func(t *testing.T) {
			runDatatest(t, f)
		})
	}
}

// Tolerances mirror the Rust suite (rust/tests/datatest.rs). Bucket boundaries
// and quantiles come from powf/sqrt, whose last bit differs across platforms
// (e.g. arm64 vs the amd64 CI runners) and math libraries, so they are compared
// within a small relative tolerance. Counts and sum are exact.
const (
	boundaryRelTol = 1e-9
	quantileRelTol = 1e-6
)

func runDatatest(t *testing.T, path string) {
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	in := parseDatatestInput(t, string(raw))

	if *rewriteDatatest {
		header := strings.TrimRight(splitHeader(string(raw)), "\n")
		if err := os.WriteFile(path, []byte(header+"\n\n"+generateGolden(in)), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}

	// Check mode: replay the values and compare the live output to the committed
	// golden. This mirrors what the Rust suite does, so both implementations are
	// checked against one shared, portable contract.
	body := splitBody(string(raw))
	if strings.TrimSpace(body) == "" {
		t.Fatalf("%s has no generated golden; run "+
			"`go test ./go/ -run TestDatatest -rewrite`", path)
	}
	exp := parseGolden(t, body)

	h := New(Params{Lo: in.lo, Hi: in.hi, ErrorBound: in.errorBound})
	for _, v := range in.values {
		h.Record(v)
	}
	snap := h.Snapshot()
	compareToGolden(t, &snap, exp)
}

// goldenBucket is a parsed OpenMetrics bucket: an upper bound and cumulative
// count. le is +Inf for the terminal bucket.
type goldenBucket struct {
	le  float64
	cum uint64
}

type goldenQuantile struct {
	q, v float64
}

type golden struct {
	buckets   []goldenBucket
	sum       int64
	count     uint64
	quantiles []goldenQuantile
}

// parseGolden reads the generated golden section back into structured values.
func parseGolden(t *testing.T, body string) golden {
	var g golden
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		key := fields[0]
		switch {
		case key == "quantile":
			g.quantiles = append(g.quantiles, goldenQuantile{
				q: mustFloat(t, fields[1]),
				v: mustFloat(t, fields[2]),
			})
		case strings.Contains(key, "_bucket{le="):
			g.buckets = append(g.buckets, goldenBucket{
				le:  parseLe(t, key),
				cum: mustUint(t, fields[1]),
			})
		case strings.HasSuffix(key, "_count"):
			g.count = mustUint(t, fields[1])
		case strings.HasSuffix(key, "_sum"):
			g.sum = mustInt(t, fields[1])
		default:
			t.Fatalf("unexpected golden line %q", line)
		}
	}
	return g
}

// parseLe extracts the le value from a token like
// `goodhistogram_bucket{le="1024"}` or `..._bucket{le="+Inf"}`.
func parseLe(t *testing.T, token string) float64 {
	start := strings.Index(token, "le=\"")
	if start < 0 {
		t.Fatalf("malformed bucket token %q", token)
	}
	rest := token[start+4:]
	end := strings.Index(rest, "\"}")
	if end < 0 {
		t.Fatalf("malformed bucket token %q", token)
	}
	s := rest[:end]
	if s == "+Inf" {
		return math.Inf(1)
	}
	return mustFloat(t, s)
}

// compareToGolden asserts the live snapshot reproduces the golden: bucket
// boundaries and quantiles within tolerance, cumulative counts, sum, and count
// exact.
func compareToGolden(t *testing.T, snap *Snapshot, exp golden) {
	buckets := snap.ToPrometheusHistogram().GetBucket()
	if len(buckets) != len(exp.buckets) {
		t.Fatalf("bucket count: got %d, golden %d", len(buckets), len(exp.buckets))
	}
	for i, b := range buckets {
		if !closeEnough(b.GetUpperBound(), exp.buckets[i].le, boundaryRelTol) {
			t.Errorf("bucket[%d] le: got %g, golden %g", i, b.GetUpperBound(), exp.buckets[i].le)
		}
		if b.GetCumulativeCount() != exp.buckets[i].cum {
			t.Errorf("bucket[%d] cumulative count: got %d, golden %d",
				i, b.GetCumulativeCount(), exp.buckets[i].cum)
		}
	}
	if snap.TotalSum != exp.sum {
		t.Errorf("sum: got %d, golden %d", snap.TotalSum, exp.sum)
	}
	if snap.TotalCount != exp.count {
		t.Errorf("count: got %d, golden %d", snap.TotalCount, exp.count)
	}
	for _, q := range exp.quantiles {
		if got := snap.ValueAtQuantile(q.q); !closeEnough(got, q.v, quantileRelTol) {
			t.Errorf("quantile q=%g: got %g, golden %g", q.q, got, q.v)
		}
	}
}

// closeEnough reports whether a and b are equal within a relative tolerance,
// with an absolute floor of 1 so values near zero don't demand impossible
// precision. Infinities must match exactly.
func closeEnough(a, b, rel float64) bool {
	if math.IsInf(a, 0) || math.IsInf(b, 0) {
		return a == b
	}
	if a == b {
		return true
	}
	scale := math.Max(math.Max(math.Abs(a), math.Abs(b)), 1.0)
	return math.Abs(a-b) <= rel*scale
}

// splitHeader returns the text before the generated marker (the description and
// input), verbatim. If there is no marker yet (a freshly authored file), the
// whole file is the header.
func splitHeader(raw string) string {
	if i := strings.Index(raw, genMarker); i >= 0 {
		return raw[:i]
	}
	return raw
}

// splitBody returns the generated section (from the marker onward), or "" if the
// file has never been rewritten.
func splitBody(raw string) string {
	if i := strings.Index(raw, genMarker); i >= 0 {
		return raw[i:]
	}
	return ""
}

// generateGolden builds a histogram from the input, records the values, and
// renders the golden section: the marker, the OpenMetrics exposition, and the
// quantiles.
func generateGolden(in datatestInput) string {
	h := New(Params{Lo: in.lo, Hi: in.hi, ErrorBound: in.errorBound})
	for _, v := range in.values {
		h.Record(v)
	}
	snap := h.Snapshot()
	prom := snap.ToPrometheusHistogram()

	var b strings.Builder
	b.WriteString(genMarker + "\n")
	fmt.Fprintf(&b, "# TYPE %s histogram\n", metricName)
	for _, bucket := range prom.GetBucket() {
		ub := bucket.GetUpperBound()
		le := "+Inf"
		if !math.IsInf(ub, 1) {
			le = strconv.FormatFloat(ub, 'g', -1, 64)
		}
		fmt.Fprintf(&b, "%s_bucket{le=%q} %d\n", metricName, le, bucket.GetCumulativeCount())
	}
	fmt.Fprintf(&b, "%s_sum %d\n", metricName, snap.TotalSum)
	fmt.Fprintf(&b, "%s_count %d\n", metricName, snap.TotalCount)
	for _, q := range datatestQuantiles {
		fmt.Fprintf(&b, "quantile %s %s\n",
			strconv.FormatFloat(q, 'g', -1, 64),
			strconv.FormatFloat(snap.ValueAtQuantile(q), 'g', -1, 64))
	}
	return b.String()
}

// parseDatatestInput reads the input keys from the header (lo, hi, error_bound,
// values). Comment and blank lines are ignored.
func parseDatatestInput(t *testing.T, raw string) datatestInput {
	in := datatestInput{lo: math.NaN(), hi: math.NaN(), errorBound: math.NaN()}
	seenValues := false
	for _, line := range strings.Split(splitHeader(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, rest, _ := strings.Cut(line, " ")
		rest = strings.TrimSpace(rest)
		switch key {
		case "lo":
			in.lo = mustFloat(t, rest)
		case "hi":
			in.hi = mustFloat(t, rest)
		case "error_bound":
			in.errorBound = mustFloat(t, rest)
		case "values":
			in.values = parseInts(t, rest)
			seenValues = true
		default:
			t.Fatalf("unknown input key %q", key)
		}
	}
	if math.IsNaN(in.lo) || math.IsNaN(in.hi) || math.IsNaN(in.errorBound) {
		t.Fatal("input must set lo, hi, and error_bound")
	}
	if !seenValues {
		t.Fatal("input must have a `values` line (may be empty)")
	}
	return in
}

func mustFloat(t *testing.T, s string) float64 {
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		t.Fatalf("bad float %q: %v", s, err)
	}
	return f
}

func mustUint(t *testing.T, s string) uint64 {
	v, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		t.Fatalf("bad uint %q: %v", s, err)
	}
	return v
}

func mustInt(t *testing.T, s string) int64 {
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		t.Fatalf("bad int %q: %v", s, err)
	}
	return v
}

func parseInts(t *testing.T, s string) []int64 {
	fields := strings.Fields(s)
	if len(fields) == 0 {
		return nil
	}
	out := make([]int64, len(fields))
	for i, f := range fields {
		v, err := strconv.ParseInt(f, 10, 64)
		if err != nil {
			t.Fatalf("bad int %q: %v", f, err)
		}
		out[i] = v
	}
	return out
}
