// Copyright 2026 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

package goodhistogram

import (
	"flag"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// Each file in ../datatest is one self-contained scenario. It has a
// hand-authored input section (the histogram params and the values to record)
// and a generated golden section (the OpenMetrics exposition plus a set of
// quantiles). The Go implementation is the source of truth: `-rewrite`
// regenerates the golden section from live Go, and a normal run re-derives it
// and fails if the committed file is stale.
//
// The Rust crate (rust/tests/datatest.rs) reads the SAME files, replays the
// values against its own implementation, and checks it reproduces the golden.
// So the two implementations are pinned to one shared, human-readable contract;
// any divergence fails CI on one side or the other. See datatest/README.md.
//
// Regenerate with:
//
//	go test ./go/ -run TestDatatest -rewrite
var rewriteDatatest = flag.Bool("rewrite", false,
	"regenerate the golden section of every datatest/*.txt from the Go implementation")

const (
	datatestDir = "../datatest"
	metricName  = "goodhistogram"
	genMarker   = "# --- generated by `go test ./go/ -run TestDatatest -rewrite`; do not edit below ---"
)

// datatestQuantiles is the set queried for every scenario: min, p25, median,
// p75, p90, p95, p99, p99.99, p99.999, max.
var datatestQuantiles = []float64{0, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99, 0.9999, 0.99999, 1}

// datatestInput is the hand-authored half of a scenario file.
type datatestInput struct {
	lo, hi, errorBound float64
	values             []int64
}

func TestDatatest(t *testing.T) {
	files, err := filepath.Glob(filepath.Join(datatestDir, "*.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if len(files) == 0 {
		t.Fatalf("no scenarios found in %s", datatestDir)
	}
	sort.Strings(files)
	for _, f := range files {
		t.Run(strings.TrimSuffix(filepath.Base(f), ".txt"), func(t *testing.T) {
			runDatatest(t, f)
		})
	}
}

func runDatatest(t *testing.T, path string) {
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	in := parseDatatestInput(t, string(raw))
	body := generateGolden(in)

	if *rewriteDatatest {
		header := strings.TrimRight(splitHeader(string(raw)), "\n")
		if err := os.WriteFile(path, []byte(header+"\n\n"+body), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}

	got := strings.TrimRight(body, "\n")
	want := strings.TrimRight(splitBody(string(raw)), "\n")
	if got != want {
		t.Fatalf("golden section is out of date with the Go implementation.\n"+
			"run `go test ./go/ -run TestDatatest -rewrite` and review the diff "+
			"(the Rust suite must then be re-run against the new golden).\n\n"+
			"--- got ---\n%s\n\n--- want ---\n%s", got, want)
	}
}

// splitHeader returns the text before the generated marker (the description and
// input), verbatim. If there is no marker yet (a freshly authored file), the
// whole file is the header.
func splitHeader(raw string) string {
	if i := strings.Index(raw, genMarker); i >= 0 {
		return raw[:i]
	}
	return raw
}

// splitBody returns the generated section (from the marker onward), or "" if the
// file has never been rewritten.
func splitBody(raw string) string {
	if i := strings.Index(raw, genMarker); i >= 0 {
		return raw[i:]
	}
	return ""
}

// generateGolden builds a histogram from the input, records the values, and
// renders the golden section: the marker, the OpenMetrics exposition, and the
// quantiles.
func generateGolden(in datatestInput) string {
	h := New(Params{Lo: in.lo, Hi: in.hi, ErrorBound: in.errorBound})
	for _, v := range in.values {
		h.Record(v)
	}
	snap := h.Snapshot()
	prom := snap.ToPrometheusHistogram()

	var b strings.Builder
	b.WriteString(genMarker + "\n")
	fmt.Fprintf(&b, "# TYPE %s histogram\n", metricName)
	for _, bucket := range prom.GetBucket() {
		ub := bucket.GetUpperBound()
		le := "+Inf"
		if !math.IsInf(ub, 1) {
			le = strconv.FormatFloat(ub, 'g', -1, 64)
		}
		fmt.Fprintf(&b, "%s_bucket{le=%q} %d\n", metricName, le, bucket.GetCumulativeCount())
	}
	fmt.Fprintf(&b, "%s_sum %d\n", metricName, snap.TotalSum)
	fmt.Fprintf(&b, "%s_count %d\n", metricName, snap.TotalCount)
	for _, q := range datatestQuantiles {
		fmt.Fprintf(&b, "quantile %s %s\n",
			strconv.FormatFloat(q, 'g', -1, 64),
			strconv.FormatFloat(snap.ValueAtQuantile(q), 'g', -1, 64))
	}
	return b.String()
}

// parseDatatestInput reads the input keys from the header (lo, hi, error_bound,
// values). Comment and blank lines are ignored.
func parseDatatestInput(t *testing.T, raw string) datatestInput {
	in := datatestInput{lo: math.NaN(), hi: math.NaN(), errorBound: math.NaN()}
	seenValues := false
	for _, line := range strings.Split(splitHeader(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, rest, _ := strings.Cut(line, " ")
		rest = strings.TrimSpace(rest)
		switch key {
		case "lo":
			in.lo = mustFloat(t, rest)
		case "hi":
			in.hi = mustFloat(t, rest)
		case "error_bound":
			in.errorBound = mustFloat(t, rest)
		case "values":
			in.values = parseInts(t, rest)
			seenValues = true
		default:
			t.Fatalf("unknown input key %q", key)
		}
	}
	if math.IsNaN(in.lo) || math.IsNaN(in.hi) || math.IsNaN(in.errorBound) {
		t.Fatal("input must set lo, hi, and error_bound")
	}
	if !seenValues {
		t.Fatal("input must have a `values` line (may be empty)")
	}
	return in
}

func mustFloat(t *testing.T, s string) float64 {
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		t.Fatalf("bad float %q: %v", s, err)
	}
	return f
}

func parseInts(t *testing.T, s string) []int64 {
	fields := strings.Fields(s)
	if len(fields) == 0 {
		return nil
	}
	out := make([]int64, len(fields))
	for i, f := range fields {
		v, err := strconv.ParseInt(f, 10, 64)
		if err != nil {
			t.Fatalf("bad int %q: %v", f, err)
		}
		out[i] = v
	}
	return out
}
