// Copyright 2026 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

package goodhistogram

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"
)

// ftoa formats a float64 with the shortest round-trippable representation.
func ftoa(f float64) string {
	return strconv.FormatFloat(f, 'g', -1, 64)
}

// The Params presets are constants that must stay identical across the Go and
// Rust implementations. TestPresets records each preset's resolved parameters
// and resulting bucketing into a golden (../datatest/presets.golden); the Rust
// suite (rust/tests/presets.rs) asserts its own preset consts reproduce it.
//
// Regenerate with:
//
//	go test ./go/ -run TestPresets -rewrite
const presetsPath = "../datatest/presets.golden"

type namedPreset struct {
	name string
	p    Params
}

// presetList maps each exported preset to a stable name shared with the Rust
// fixture reader.
func presetList() []namedPreset {
	return []namedPreset{
		{"CoarseParams", CoarseParams},
		{"StandardParams", StandardParams},
		{"FineParams", FineParams},
		{"HiResLatencyParams", HiResLatencyParams},
		{"IOLatencyParams", IOLatencyParams},
		{"ResponseTimeParams", ResponseTimeParams},
		{"LongRunningParams", LongRunningParams},
		{"DataSizeParams", DataSizeParams},
		{"MemoryUsageParams", MemoryUsageParams},
	}
}

func generatePresets() string {
	var b strings.Builder
	b.WriteString("# goodhistogram Params presets, generated from Go.\n")
	b.WriteString("# Generated by: go test ./go/ -run TestPresets -rewrite\n")
	b.WriteString("# Verified by this test and rust/tests/presets.rs.\n")
	b.WriteString("# Fields: preset <name> <lo> <hi> <error_bound> <schema> <num_buckets>\n")
	for _, np := range presetList() {
		resolved := np.p.withDefaults()
		snap := New(np.p).Snapshot()
		fmt.Fprintf(&b, "preset %s %s %s %s %d %d\n",
			np.name, ftoa(resolved.Lo), ftoa(resolved.Hi), ftoa(resolved.ErrorBound),
			snap.Schema(), len(snap.Counts))
	}
	return b.String()
}

func TestPresets(t *testing.T) {
	if *rewriteDatatest {
		if err := os.WriteFile(presetsPath, []byte(generatePresets()), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}

	raw, err := os.ReadFile(presetsPath)
	if err != nil {
		t.Fatalf("%v\nrun `go test ./go/ -run TestPresets -rewrite`", err)
	}
	want := parsePresets(t, string(raw))
	if len(want) != len(presetList()) {
		t.Fatalf("golden has %d presets, code has %d; run -rewrite", len(want), len(presetList()))
	}
	for _, np := range presetList() {
		g, ok := want[np.name]
		if !ok {
			t.Errorf("preset %s missing from golden", np.name)
			continue
		}
		resolved := np.p.withDefaults()
		snap := New(np.p).Snapshot()
		// lo/hi are exact literals; error_bound comes from powf and is compared
		// with tolerance; schema/num_buckets are exact.
		if resolved.Lo != g.lo {
			t.Errorf("%s lo: got %g, golden %g", np.name, resolved.Lo, g.lo)
		}
		if resolved.Hi != g.hi {
			t.Errorf("%s hi: got %g, golden %g", np.name, resolved.Hi, g.hi)
		}
		if !closeEnough(resolved.ErrorBound, g.errorBound, boundaryRelTol) {
			t.Errorf("%s error_bound: got %g, golden %g", np.name, resolved.ErrorBound, g.errorBound)
		}
		if snap.Schema() != g.schema {
			t.Errorf("%s schema: got %d, golden %d", np.name, snap.Schema(), g.schema)
		}
		if len(snap.Counts) != g.numBuckets {
			t.Errorf("%s num_buckets: got %d, golden %d", np.name, len(snap.Counts), g.numBuckets)
		}
	}
}

type presetGolden struct {
	lo, hi, errorBound float64
	schema             int32
	numBuckets         int
}

func parsePresets(t *testing.T, raw string) map[string]presetGolden {
	out := make(map[string]presetGolden)
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		f := strings.Fields(line)
		if len(f) != 7 || f[0] != "preset" {
			t.Fatalf("malformed preset line %q", line)
		}
		out[f[1]] = presetGolden{
			lo:         mustFloat(t, f[2]),
			hi:         mustFloat(t, f[3]),
			errorBound: mustFloat(t, f[4]),
			schema:     int32(mustInt(t, f[5])),
			numBuckets: int(mustInt(t, f[6])),
		}
	}
	return out
}
